### ISSUE TITLE
JavaScript studies

### ISSUE THREAD

**Issue by gabrielluizep** [G-A-L-E-O-N-G-A-D/PROJECT-X#3]
All the JS module seen
![image](https://user-images.githubusercontent.com/70443613/100395983-f953ba00-3021-11eb-9e20-f406b96a0095.png)

**Comment by leonardodod** [comment]
Done !
![Opera Instantâneo_2020-11-26_225754_app rocketseat com br](https://user-images.githubusercontent.com/74744977/100402694-aab31980-303b-11eb-9a9f-1ab5106f2be6.png)
